language: php

cache:
    directories:
        - $HOME/.composer/cache
        - vendor

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.1.*
  - SYMFONY_VERSION=5.2.*

matrix:
  include:
    - php: 7.2
      env: SYMFONY_VERSION=''
    - php: 7.3
      env: SYMFONY_VERSION=''
    - php: 7.4
      env: SYMFONY_VERSION=''
  fast_finish: true

addons:
    apt:
        packages:
            - language-pack-fr
            - language-pack-en

before_install:
    # Disable XDebug to speed up test execution. (Ignore failures if platform does not had the extension installed)
    - phpenv config-rm xdebug.ini || return 0
    # Enable MongoDB extension
    - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini || return 0
    - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini || return 0

install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer --no-update require symfony/framework-bundle:${SYMFONY_VERSION}; fi;
    - travis_retry composer update $COMPOSER_FLAGS
    - composer info

script:
  - make test
  - make qa
  - make license
  - make changelog
